# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
#         default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
#         default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"

  say_location:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "- in ${{ github.event.inputs.home }}!"
